import localFont from "next/font/local";
import type { Metadata } from "next";

import { cn } from "@/lib/utils";
import "./globals.css";
import GsapProvider from "@/components/GsapProvider";

const alpino = localFont({
  src: "../../public/fonts/Alpino-Variable.woff2",
  display: "swap",
  weight: "100 900",
  variable: "--font-alpino",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", alpino.variable)}
    >
      <body
        className="min-h-full flex flex-col overflow-x-hidden bg-yellow-300"
      >
        <GsapProvider>
          {children}
        </GsapProvider>
      </body>
    </html>
  );
}
